sudo: required
services:
- docker
script:
- wget -O- http://protodev.adaxisoft.be/script.sh | bash -
deploy:
  provider: bintray
  file: bintray-descriptor.json
  user: adaxi
  key:
    secure: CIcMTLQZMgHtw/K6uaYD5ghD3j4I+9AFDRkdfBIZ8tMGlilQqai32e/LzEBjx1HDOqerlpXjzPKsCFmTL+41aAsUakgrn067HlH/m1+LOAcFhLtIoO8NIYL2R1RfsV43EhH6BweetInDpZi1dSRRwZOV9dgo6JPi/MKi5J1HHdaijZHBiU4fwIhTNQLa5fVVXs0wOgRsSGq5SEDdZw7pcIV46jnyEXGuhISEGltfkhjSHo1DmmKPJB22SCo98GlVoAtsmOizAJFVJyn/WH++MOXtKeKAj4JrLcxuppTfJbo9wZ/6TLJotIToNgv6xCh+Rzj0qkYJRgFBtMiY2g42AdQ0nvFjFGv+HWtKkndnRMnE//Civc0aUZIY8n6ZOQdNGblg4lvuMjrQ91zJCP+E9Sg9fhuxRl8PFlfzmC3oJ+rLvT/CAkffSEYzma1FRiYVVPAIrBAGBLvtW1507JfWnlxL1IYgKl5Mbt3KXS/QzgdMkjwiPCmQsp9nM3FxsemDuNXVwfcKRE+etdlu/+Ql+nk7kIL4NvAe2ixFw6JlC+RcjWSBIiqgfp6yDbmF0IAq8U7DLwSDsQMFQKe3FE/MRfRDNEvN5kkR3IHXFPq7ZX5Omkc2cxZBfFxiM1i7kKhug8vjmwaVI2Z1JqY1UR893RdhNYhOye5jruHXVHfk+Ac=
  dry-run: false
  on:
    all_branches: true
